### ISSUE TITLE
Finder disconnection causes chromium to start again

### ISSUE THREAD

**Issue by shivamadhavan** [shivamadhavan/orpa-nodes#7]
## Expected Behavior
The Chromium launched by Finder( through puppeteer) should not disconnect when runtime and editor are running

## Current Behavior
There are times when the blue chromium loses connection with node red.
the introspector highlights on the blue chrome browser, but nothing goes back to the IDE.
when I press one of the magnify glass buttons a new blue chrome starts up.

## Steps to Reproduce

1.
2.
3.
4.

## Environment
| Component | Versions |
| ------------- | ------------- |
| Operating System |  |
| Node Js |  |
| NPM |  |
| Node Js |  |
|Opal-Node-Red|  |

**Comment by msivadas** [comment]
some console logs: 

```Starting New
Launching ws://127.0.0.1:52890/devtools/browser/d415167c-fe9a-4994-8eb6-5f13548ce48f
gotBrowser
GetPages
Page %s not found, creating new
gotPage
Now: about:blank
Required: http://access.wftcloud.com:8017/sap/bc/gui/sap/its/webgui
1 _-_ FinderPluginSvcPage
Injecting All ExposeFunctions
NowError 1 notifyObjectFound
1
Module Directory : /Users/msivadas/opal3mar/node_modules/opal-page-object-finder
Attached N [undefined], [], [http://access.wftcloud.com:8017/sap/bc/gui/sap/its/webgui]
Navigation Complete http://access.wftcloud.com:8017/sap/bc/gui/sap/its/webgui
SRV :::: Message {"id":67,"method":"FinderPluginSvcPage.startFinder","params":{"sessionId":"1154ef10.463421","id":"1"}}
startFinder Params {"sessionId":"1154ef10.463421","id":"1"}
{ id: '1154ef10.463421',
  browserWSEndpoint: 'ws://127.0.0.1:52890/devtools/browser/d415167c-fe9a-4994-8eb6-5f13548ce48f',
  targetId: '(EBBF7DC74082D479B56EAF7B4907FB2)',
  launchOpts: 
   { headless: false,
     executablePath: '/Users/msivadas/opal3mar/node_modules/opal-puppeteer/.local-chromium/mac-515411/chrome-mac/Chromium.app/Contents/MacOS/Chromium' } }
getBrowser
Connecting ws://127.0.0.1:52890/devtools/browser/d415167c-fe9a-4994-8eb6-5f13548ce48f
GetPages
Page (EBBF7DC74082D479B56EAF7B4907FB2) found
Attached: http://access.wftcloud.com:8017/sap/bc/gui/sap/its/webgui
Activate Finder true
startFinder Params {"sessionId":"1154ef10.463421"}
{ id: '1154ef10.463421',
  browserWSEndpoint: 'ws://127.0.0.1:52890/devtools/browser/d415167c-fe9a-4994-8eb6-5f13548ce48f',
  targetId: '(EBBF7DC74082D479B56EAF7B4907FB2)',
  launchOpts: 
   { headless: false,
     executablePath: '/Users/msivadas/opal3mar/node_modules/opal-puppeteer/.local-chromium/mac-515411/chrome-mac/Chromium.app/Contents/MacOS/Chromium' } }
getBrowser
Connecting ws://127.0.0.1:52890/devtools/browser/d415167c-fe9a-4994-8eb6-5f13548ce48f
GetPages
Page (EBBF7DC74082D479B56EAF7B4907FB2) found
Target Destroyed (50E68247B0F4E5A915633FE103A6F210)
Target Destroyed (EBBF7DC74082D479B56EAF7B4907FB2)
Target Destroyed (3A6DEB09DED1A3753A9E88B655DFEA97)
Target Destroyed (B665496F27510D64AEE58C2B1CE89704)
Target Destroyed (D059FA606B9452DC9996F53E2B977DF7)
SRV :::: Message {"id":68,"method":"FinderPluginSvcPage.stopFinder","params":{"sessionId":"1154ef10.463421","id":"1"}}
stopFinder Params {"sessionId":"1154ef10.463421","id":"1"}
{ id: '1154ef10.463421',
  browserWSEndpoint: 'ws://127.0.0.1:52890/devtools/browser/d415167c-fe9a-4994-8eb6-5f13548ce48f',
  targetId: '(EBBF7DC74082D479B56EAF7B4907FB2)',
  launchOpts: 
   { headless: false,
     executablePath: '/Users/msivadas/opal3mar/node_modules/opal-puppeteer/.local-chromium/mac-515411/chrome-mac/Chromium.app/Contents/MacOS/Chromium' } }
getBrowser
Connecting ws://127.0.0.1:52890/devtools/browser/d415167c-fe9a-4994-8eb6-5f13548ce48f
{ Error: connect ECONNREFUSED 127.0.0.1:52890
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 52890 }
GetPages
TypeError: Cannot read property 'pages' of undefined
    at FinderPluginSvc.getPage (/Users/msivadas/opal3mar/node_modules/opal-page-object-finder/finder.plugin.svc.js:318:37)
    at FinderPluginSvc.stopFinder (/Users/msivadas/opal3mar/node_modules/opal-page-object-finder/finder.plugin.svc.js:469:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
SRV :::: Message {"id":69,"method":"FinderPluginSvcPage.connectToBrowser","params":{"sessionId":"1154ef10.463421","url":"","id":"1"}}
connectToBrowser {"sessionId":"1154ef10.463421","url":"","id":"1"}
getBrowser
Connecting ws://127.0.0.1:52890/devtools/browser/d415167c-fe9a-4994-8eb6-5f13548ce48f
{ Error: connect ECONNREFUSED 127.0.0.1:52890
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 52890 }
getBrowser
Starting New
Launching ws://127.0.0.1:53333/devtools/browser/bfe572e5-47cb-43ce-bd21-218e3ba8fb4f
gotBrowser
GetPages
Page %s not found, creating new
gotPage
Now: about:blank
Required: 
1 _-_ FinderPluginSvcPage
Injecting All ExposeFunctions
NowError 1 notifyObjectFound
1
Module Directory : /Users/msivadas/opal3mar/node_modules/opal-page-object-finder
Nvigation Cancelled
SRV :::: Message {"id":70,"method":"FinderPluginSvcPage.startFinder","params":{"sessionId":"586946f4.ae59d8","id":"1"}}
startFinder Params {"sessionId":"586946f4.ae59d8","id":"1"}
{ id: '586946f4.ae59d8',
  browserWSEndpoint: 'ws://127.0.0.1:53333/devtools/browser/bfe572e5-47cb-43ce-bd21-218e3ba8fb4f',
  targetId: '(ECCB944B071C79C38F66B10BE35B98AE)',
  launchOpts: 
   { headless: false,
     executablePath: '/Users/msivadas/opal3mar/node_modules/opal-puppeteer/.local-chromium/mac-515411/chrome-mac/Chromium.app/Contents/MacOS/Chromium' } }
getBrowser
Connecting ws://127.0.0.1:53333/devtools/browser/bfe572e5-47cb-43ce-bd21-218e3ba8fb4f
GetPages
Page (ECCB944B071C79C38F66B10BE35B98AE) found
Target Destroyed (ECCB944B071C79C38F66B10BE35B98AE)
Target Destroyed (5486309B2C90491D58625EEF5530534F)
SRV :::: Message {"id":71,"method":"FinderPluginSvcPage.stopFinder","params":{"sessionId":"586946f4.ae59d8","id":"1"}}
stopFinder Params {"sessionId":"586946f4.ae59d8","id":"1"}
{ id: '586946f4.ae59d8',
  browserWSEndpoint: 'ws://127.0.0.1:53333/devtools/browser/bfe572e5-47cb-43ce-bd21-218e3ba8fb4f',
  targetId: '(ECCB944B071C79C38F66B10BE35B98AE)',
  launchOpts: 
   { headless: false,
     executablePath: '/Users/msivadas/opal3mar/node_modules/opal-puppeteer/.local-chromium/mac-515411/chrome-mac/Chromium.app/Contents/MacOS/Chromium' } }
getBrowser
Connecting ws://127.0.0.1:53333/devtools/browser/bfe572e5-47cb-43ce-bd21-218e3ba8fb4f
{ Error: connect ECONNREFUSED 127.0.0.1:53333
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 53333 }
GetPages
TypeError: Cannot read property 'pages' of undefined
```
